### ISSUE TITLE
The split of train/dev/test sets

### ISSUE THREAD

**Issue by Veason-silverbullet** [taoqi98/KIM#1]
Hi, could you please provide the code (or information) of dataset preparation?

Since the MIND test set is not available, it is necessary to know how to generate experimental train/dev/test sets. Could you please the code (or information) to generate 'train_sam2.tsv', 'val_sam2.tsv' and 'test_sam2.tsv' from the MIND-small dataset?

**Comment by taoqi98** [comment]
Thanks for your suggestion. I will upload these codes in this week.
