### ISSUE TITLE
The files "entity2id.txt", "entity_embedding.npy", "KGGraph.json" 

### ISSUE THREAD

**Issue by Gongur18** [taoqi98/KIM#2]
Hi, could you please provide the files "entity2id.txt", "entity_embedding.npy", "KGGraph.json", or how to get  it?

I have tried to get these files from MIND and wikiData, but there was an KeyError that some entities don't exist.

**Comment by taoqi98** [comment]
Thank you for your attention on our work. Due to license issue of MIND dataset, I am not sure whether I can publicly share processed KG data on MIND. Thus, I want to privately share KG data with you. You can send an email to me (taoqi.qt@gmail.com) and I will reply the KG data ASAP.

**Comment by wylapp** [comment]
@Gongur18 Hi, do you still have these files, if you do, could you please share them with me? thanks!

**Comment by taoqi98** [comment]
> @Gongur18 Hi, do you still have these files, if you do, could you please share them with me? thanks!

Hi, you can access these files by sending an email to me: taoqi.qt@gmail.com.
