### ISSUE TITLE
一些报错信息

### ISSUE THREAD

**Issue by aaarira** [taoqi98/KIM#4]
ValueError: Dimension must be 5 but is 4 for '{{node attention_1/transpose_7}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](attention_1/truediv, attention_1/transpose_7/perm)' with input shapes: [?,20,?,20,?], [4].有没有遇到过这种错误呢

**Comment by taoqi98** [comment]
This is caused by the version conflict between tensorflow and keras. The codes can be successfully excuted under tensorflow-gpu == 1.13.0 and keras == 2.2.4 .

**Comment by zhangrc2023** [comment]
> ValueError: Dimension must be 5 but is 4 for '{{node attention_1/transpose_7}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](attention_1/truediv, attention_1/transpose_7/perm)' with input shapes: [?,20,?,20,?], [4].有没有遇到过这种错误呢

hi, i wonder if you have successfully reproduced this papers?
