### ISSUE TITLE
Source of Knowledge Graph

### ISSUE THREAD

**Issue by Ruixinhua** [taoqi98/KIM#5]
Hi.

Could you please provide the source of the knowledge graph? Where can I download the knowledge graph used in the paper?
Currently, I am using News Graph (Liu, D., Bai, T., Lian, J., Sun, G., Zhao, W. X., Wen, J.-R., & Xie, X. (2019). News Graph: An Enhanced Knowledge Graph for News Recommendation. 7. ) in KRED (https://github.com/danyang-liu/KRED)

Thank you very much!

**Comment by taoqi98** [comment]
Due to potential license issues, I can privately share the KG data with you. Please send an email to me to query these data. My email is taoqi.qt@gmail.com.
