### ISSUE TITLE
KG graph

### ISSUE THREAD

**Issue by Clytzes** [taoqi98/KIM#6]
代码中的kggraph，也就是KGGraph.json这个文件是如何构造的呢？是利用OPENKG中的tripple2id来聚合每个头节点下的尾节点吗？是否去重呢？

**Comment by taoqi98** [comment]
Hi, the KG Graph used in KIM is provided by the MIND paper. The detailed construction algorithm of the KG can be found in this paper https://arxiv.org/pdf/1910.11494.pdf .
