### ISSUE TITLE
Blas GEMM launch failed

### ISSUE THREAD

**Issue by zhangrc2023** [taoqi98/KIM#7]
请问这个bug如何解决？我的tensorflow-gpu=1.13.1，keras=2.2.4，显卡是A100，cuda=10.0.130？尝试过CPU能跑起来，换到CPU就不行了？网上查了很多办法都不行。。。
![屏幕截图 2023-11-14 213420](https://github.com/taoqi98/KIM/assets/145538153/09c21307-e901-4149-917b-5f2936d46fef)

**Comment by taoqi98** [comment]
你好，大概率由于1.13.1的tensorflow和你A100显卡对应的cuda无法兼容导致的，可以参考https://www.zhihu.com/question/449281298
